### ISSUE TITLE
Read satellite data from AWS

### ISSUE THREAD

**Issue by remi-braun** [sertit/eoreader#104]
EOReader is able to read products stored on the cloud.
The main issue is that the format of these products may be different from the one delivred elsewhere (i.e. no more SAFE format)

There is a community need for that, see #102 

___

# Sentinel-2
- [x] [`sentinel-2-l1c`](https://stacindex.org/catalogs/earth-search#/43bjKKcJQfxYaT1ir3Ep6uENfjEoQrjkzhYe) - from [`arn:aws:s3:::sentinel-s2-l1c`](https://registry.opendata.aws/sentinel-2/) (Sinergise) - ✔️ 
- [x] [`sentinel-2-l2a`](https://stacindex.org/catalogs/earth-search#/43bjKKcJQfxYaT1ir3Ep6uENfjEoQrjkzhd2) - from [`arn:aws:s3:::sentinel-cogs` ](https://registry.opendata.aws/sentinel-2-l2a-cogs/)(Element84) - ✔️ 
- [x] `sentinel-s2-l2a` - from [`arn:aws:s3:::sentinel-s2-l2a`](https://registry.opendata.aws/sentinel-2/) (Sinergise) - ✔️ 
# Sentinel-1
- ❌ [`sentinel-1-grd`](https://stacindex.org/catalogs/earth-search#/43bjKKcJQfxYaT1ir3Ep6uENfjEoQrdDSGwd) - from [`arn:aws:s3:::sentinel-s1-l1c`](https://registry.opendata.aws/sentinel-1/) (Sinergise) - ❌ **WON'T DO** for now as SNAP doesn't handle AWS-stored products
# Other
- [x] [`landsat-c2-l1` and `landsat-c2-l2`](https://stacindex.org/catalogs/earth-search#/h1csNSDZ6exe2pHjNDjm3rmSbztdsZdWyF) - from [`arn:aws:s3:::usgs-landsat/collection02/`](https://registry.opendata.aws/usgs-landsat/index.html) (USGS) - ✔ ️Was already OK as their formatting are the same on cloud and on disk
- Umbra open data, Maxar open data, Landsat etc... (other issues)
   - Handle Umbra as a new product #114 
   - Handle STAC Items as entry points #118 

Then look at MPC data (delayed, as I need to register)
- [MPC](https://stacindex.org/catalogs/microsoft-pc#/)

Don't forget to had documentation and a notebook about Cloud-stored products

**Comment by remi-braun** [comment]
@bcerripromethee If you clone the 0.21.0 branch, could you tell me if it fits your needs ?
Note that right now EOReader is not able to ingest a STAC object, but it'll be soon I hope.

**Comment by bcerripromethee** [comment]
Alright, i'll test it ;)

I just initiate the Reader with the path of the Element84 item (such as a random Sentinel-2 product) ?

**Comment by remi-braun** [comment]
You can find some help here: https://github.com/sertit/eoreader/blob/0.21.0/docs/notebooks/aws.ipynb :)

**Comment by remi-braun** [comment]
This should work:

```python
from eoreader.reader import Reader
import tempenv
from sertit import s3
from eoreader.bands import BLUE
with tempenv.TemporaryEnvironment({
    "AWS_S3_ENDPOINT": "s3.us-west-2.amazonaws.com",
}):
    with s3.temp_s3():
        path = r"s3://sentinel-cogs/sentinel-s2-l2a-cogs/40/V/DR/2023/11/S2A_40VDR_20231114_0_L2A"
        prod = Reader().open(path)
        blue = prod.load([BLUE])[BLUE]
```

Give the S3 path you find in your catalogue: 
![2023-11-14_11h55_52](https://github.com/sertit/eoreader/assets/67311115/d31b26b5-a74d-4c50-adda-83a381d33df5)

**Comment by bcerripromethee** [comment]
I tried your methodology but it doesn't seems to work, i got this error :
`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

**Comment by remi-braun** [comment]
Sorry, I updated the code hereover.

The only difference is to set `""` to `"AWS_SECRET_ACCESS_KEY"` and `"AWS_ACCESS_KEY_ID"`

**Comment by bcerripromethee** [comment]
You mean like this ? ->
```python
s2_path = r"s3://sentinel-s2-l2a/tiles/40/V/DR/2023/11/14/0/"

with tempenv.TemporaryEnvironment({"AWS_S3_ENDPOINT": "s3.eu-central-1.amazonaws.com",
                                   "AWS_SECRET_ACCESS_KEY": "",
                                   "AWS_ACCESS_KEY_ID": ""}):
    with s3.temp_s3(requester_pays=True):
        prod = Reader().open(s2_path)
        print(prod)
```

**Comment by remi-braun** [comment]
No, copy paste my piece of code 😉 
You need to remove `requester_pays=True` (or set it to False)

**Comment by bcerripromethee** [comment]
Even by copy-pasting your code i still get the message `botocore.exceptions.NoCredentialsError: Unable to locate credentials`, it's weird

**Comment by remi-braun** [comment]
Ok, let's use only `rasterio` and `cloudpathlib`, and not `sertit` libraries.
It will complicate a bit your code, though:

```python
import os
from cloudpathlib import S3Client, AnyPath
import rasterio
from eoreader.reader import Reader

# Create your S3 path with cloudpathlib
aws_endpoint = "s3.us-west-2.amazonaws.com"
client = S3Client(endpoint_url=f"https://{aws_endpoint }")
client.set_as_default_client()

# Path
path = "s3://sentinel-cogs/sentinel-s2-l2a-cogs/40/V/DR/2023/11/S2A_40VDR_20231114_0_L2A"

# Create a rasterio env to enable reading on S3
with rasterio.Env(AWS_S3_ENDPOINT=aws_endpoint):
    # Open your product
    prod = Reader().open(path)
    print(prod)

**Comment by bcerripromethee** [comment]
I still get the same error message 😅

**Comment by remi-braun** [comment]
Do you have any .aws folder somewhere in your session ? This could jam your connection 🤔 
For the record, this is not an issue with EOReader, but with botocore, to access S3 files

**Comment by remi-braun** [comment]
Maybe this:

```python
import os
from cloudpathlib import S3Client, AnyPath
import rasterio
from eoreader.reader import Reader
# Create your S3 path with cloudpathlib
aws_endpoint = "s3.us-west-2.amazonaws.com"
client = S3Client(endpoint_url=f"https://{aws_endpoint}", no_sign_request=True)
client.set_as_default_client()
# Path
path = "s3://sentinel-cogs/sentinel-s2-l2a-cogs/40/V/DR/2023/11/S2A_40VDR_20231114_0_L2A"
# Create a rasterio env to enable reading on S3
with rasterio.Env(AWS_S3_ENDPOINT=aws_endpoint, AWS_NO_SIGN_REQUEST="YES"):
    # Open your product
    prod = Reader().open(path)
    print(prod)

**Comment by bcerripromethee** [comment]
Your last solution worked !!!! 🍾🍾🍾🍾

**Comment by remi-braun** [comment]
Note that with `sertit[full]>=1.32.1`, the following will work (if the environment variable `AWS_S3_ENDPOINT` is empty, if not set it with `tempenv` like above):

```python
  with s3.temp_s3("s3.us-west-2.amazonaws.com", no_sign_request=True):
      path = r"s3://sentinel-cogs/sentinel-s2-l2a-cogs/40/V/DR/2023/11/S2A_40VDR_20231114_0_L2A"
      prod = Reader().open(path)
      print(prod)
```

```
eoreader.S2E84Product 'S2A_MSIL2A_20231114T074151_N0509_R092_T40VDR_20231114T081855'
Attributes:
	condensed_name: 20231114T074151_S2_T40VDR_L2A_081855
	path: s3://sentinel-cogs/sentinel-s2-l2a-cogs/40/V/DR/2023/11/S2A_40VDR_20231114_0_L2A
	constellation: Sentinel-2 stored on AWS and processed by Element84
	sensor type: Optical
	product type: MSIL2A
	default pixel size: 10.0
	default resolution: 10.0
	acquisition datetime: 2023-11-14T07:41:51
	band mapping:
		COASTAL_AEROSOL: 01
		BLUE: 02
		GREEN: 03
		RED: 04
		VEGETATION_RED_EDGE_1: 05
		VEGETATION_RED_EDGE_2: 06
		VEGETATION_RED_EDGE_3: 07
		NIR: 08
		NARROW_NIR: 8A
		WATER_VAPOUR: 09
		SWIR_1: 11
		SWIR_2: 12
	needs extraction: False
	cloud cover: 99.999058
	tile name: T40VDR

**Comment by remi-braun** [comment]
I'm closing this issue, but it still links to others (Umbra, STAC, MPC...) that are open.

**Comment by remi-braun** [comment]
0.21.0 is up today :)
